# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='attach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='secret_key',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
