# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20171122_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='worker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
